name: Sports Edge Physiotherapy
favicon: null
layout_spectrum: 0.1490179819520563
typography_spectrum: 0.2367913401685655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8301073033362627
  lightness: 0.3624189121183008
  saturation: 0.5767816721927375
  rhythmicContrast: 0.3638480647932738
purpose: []
